// sst-plugininfra version strings for the browser build (normally generated by CMake from git).

#include <sst/plugininfra/version_information.h>

#ifndef OBXF_WEB_VERSION
#define OBXF_WEB_VERSION "1.1.0"
#endif

namespace sst::plugininfra
{
const char *VersionInformation::git_commit_hash{"b08ffb6"};
const char *VersionInformation::git_branch{"main"};
const char *VersionInformation::git_tag{""};
const char *VersionInformation::git_implied_display_version{OBXF_WEB_VERSION " (WebCLAP UI prototype)"};
const char *VersionInformation::project_version_major{"1"};
const char *VersionInformation::project_version_minor{"1"};
const char *VersionInformation::project_version_patch{"0"};
const char *VersionInformation::project_version_tweak{"0"};
const char *VersionInformation::project_version{OBXF_WEB_VERSION};
const char *VersionInformation::project_version_and_hash{OBXF_WEB_VERSION ".b08ffb6"};
const char *VersionInformation::project_version_full{OBXF_WEB_VERSION ".0"};
const char *VersionInformation::cmake_source_dir{""};
const char *VersionInformation::cmake_binary_dir{""};
const char *VersionInformation::cmake_install_prefix{"/"};
const char *VersionInformation::cmake_compiler_id{"Clang"};
const char *VersionInformation::cmake_compiler_version{__clang_version__};
const char *VersionInformation::cmake_compiler{"Emscripten"};
const char *VersionInformation::cmake_system_name{"Emscripten"};
const char *VersionInformation::build_date{__DATE__};
const char *VersionInformation::build_year{""};
const char *VersionInformation::build_time{__TIME__};
const char *VersionInformation::build_host{"emscripten"};
} // namespace sst::plugininfra
