#!/usr/bin/env python3
"""Generate JUCE-style BinaryData.h/.cpp without juceaide (which would need a native JUCE build).

Identifiers follow juce_build_tools::makeValidIdentifier, so code written against juceaide's output
(BinaryData::icon_svg, getNamedResource ("knoblayer1_svg", size), ...) compiles unchanged.

Usage: binary_data.py <out_dir> <namespace> <file>...
"""

import os
import sys

ALLOWED = set("_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
RESERVED = {"auto", "break", "case", "char", "class", "const", "continue", "default", "delete", "do", "double",
            "else", "enum", "float", "for", "goto", "if", "int", "long", "new", "private", "public", "return",
            "short", "signed", "sizeof", "static", "struct", "switch", "this", "union", "unsigned", "void",
            "while", "namespace", "template", "true", "false", "typename", "using"}


def identifier(filename):
    name = filename
    for c in ".,;:/@":
        name = name.replace(c, "_")
    name = "".join(c for c in name.replace(" ", "_") if c in ALLOWED)
    if not name:
        name = "unknown"
    if name[0].isdigit():
        name = "_" + name
    if name in RESERVED:
        name += "_"
    return name


def main():
    out_dir, namespace, files = sys.argv[1], sys.argv[2], sys.argv[3:]
    os.makedirs(out_dir, exist_ok=True)

    names, used = [], set()
    for path in files:
        base = identifier(os.path.basename(path))
        name, n = base, 2
        while name in used:
            name, n = f"{base}{n}", n + 1
        used.add(name)
        names.append(name)

    header = [f"// Generated by scripts/binary_data.py, do not edit.", "#pragma once", "",
              f"namespace {namespace}", "{"]
    for name, path in zip(names, files):
        header.append(f"    extern const char* {name};")
        header.append(f"    const int {name}Size = {os.path.getsize(path)};")
    header += ["",
               f"    const int namedResourceListSize = {len(names)};",
               "    extern const char* namedResourceList[];",
               "    extern const char* originalFilenames[];",
               "    const char* getNamedResource (const char* resourceNameUTF8, int& dataSizeInBytes);",
               "    const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8);",
               "}", ""]
    open(os.path.join(out_dir, f"{namespace}.h"), "w").write("\n".join(header))

    cpp = [f"// Generated by scripts/binary_data.py, do not edit.", f'#include "{namespace}.h"', "#include <cstring>", ""]
    for i, path in enumerate(files):
        data = open(path, "rb").read() + b"\0"
        cpp.append(f"static const unsigned char resource_{i}[] = {{")
        for offset in range(0, len(data), 32):
            cpp.append("    " + ",".join(str(b) for b in data[offset:offset + 32]) + ",")
        cpp.append("};")
    cpp += ["", f"namespace {namespace}", "{"]
    for i, name in enumerate(names):
        cpp.append(f"    const char* {name} = (const char*) resource_{i};")
    cpp.append("")
    cpp.append("    const char* namedResourceList[] = {")
    cpp += [f'        "{name}",' for name in names]
    cpp.append("    };")
    cpp.append("    const char* originalFilenames[] = {")
    cpp += [f'        "{os.path.basename(path)}",' for path in files]
    cpp.append("    };")
    cpp += ["",
            "    const char* getNamedResource (const char* resourceNameUTF8, int& numBytes)",
            "    {"]
    for name in names:
        cpp.append(f'        if (std::strcmp (resourceNameUTF8, "{name}") == 0) {{ numBytes = {name}Size; return {name}; }}')
    cpp += ["        numBytes = 0;", "        return nullptr;", "    }", "",
            "    const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8)",
            "    {",
            "        for (int i = 0; i < namedResourceListSize; ++i)",
            "            if (std::strcmp (namedResourceList[i], resourceNameUTF8) == 0)",
            "                return originalFilenames[i];",
            "        return nullptr;",
            "    }",
            "}", ""]
    open(os.path.join(out_dir, f"{namespace}.cpp"), "w").write("\n".join(cpp))


if __name__ == "__main__":
    main()
